# Generated by Django 5.1.2 on 2024-10-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Todo list', 'verbose_name_plural': 'Todo list'},
        ),
    ]
